export default [
  `10 Reasons to Open This Email (Open To Find Out!)`,
  `FREE 40 POUND BAG OF JELLY BEANS!`,
  `Re: Trademark Request for "Neato Burrito"`,
  `Your Weird Dreams Explained: No, You Shouldn't Get a Pet Panda`,
  `Application Accepted – Cheesecake Club of America`,
  `Casting Call – Seeking Actress To Play Rose in Titanic Reboot`,
  `20 Step Program: Change Your Innner Monologue's Voice to Jame Earl Jones`,
  `[NOTIFICATION] - New Post in Forum "Did E.T. leave me emotionally scarred?"`,
  `Highly Reputable Science Magazine: French Fries are the New Superfood`,
  `Fw: Fw: Fw: Fw: omg omg omg check this out rn!`,
  `Never Gonna Give You Up, Never Gonna Let You Down, Never Gonna Run Around and...`,
  `Forward 2 10 ppl or u will drown in confetti 4 real`,
  `President Barack Obama's Favorite Cat Videos`,
  `The Results Are In! You are 96% Liz Lemon`,
  `Mmmbop, Ba Duba Dop, Ba Du Bop, Ba Duba Dop`,
  `~*~ rEmEmBeR tYpInG sHiT lIkE tHiS ~*~`,
]
